apiVersion: v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-registry
webhooks:
- name: io.docker.admission-registry
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - "*"
    resources:
    - pods
  clientConfig:
    service:
      name: admission-registry
      namespace: default
      path: "/validate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtakNDQW9LZ0F3SUJBZ0lVWUpsRWRxdUM1Rk15dit2dmNhV3pTOFFGdjNFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFXcHBibWN4RURBT0JnTlZCQWNUQjBKbAphV3BwYm1jeEREQUtCZ05WQkFvVEEwczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByClpXSmxjbTVsZEdWek1CNFhEVEkwTURVeE5URXlOVE13TUZvWERUSTVNRFV4TkRFeU5UTXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFXcHBibWN4RURBT0JnTlZCQWNUQjBKbGFXcHBibWN4RERBSwpCZ05WQkFvVEEwczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByWldKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeXhoMHdnWk9Sa1UwU0YvOE1OVHoKR2lJUFFpSVJIZGVqN1NaTXVIN0lCdW5pWUIyN3lGZXl5SlBoRnV2RDc2azBwNnNSNXk5TXJudjJDMy80UEo2WQp0TUlnendnbDBxWVNoYzdLblRiY05yNUxrWG9oRi9iQzMyZzE2QU9rSWJRL2MrSVFTTHRtb2RheHJoUlZKSUJaCjNHaW9wNmE3ZkpmRFQ0UGxrZ1BVOU5VRjlTMmdtWmt6MW1nMGFxaG9lakdITitsMW1ERXhUVHFnYWllbHFZNGIKVmVsVjBobjVzaGpRanRUZE82TC95aElWUEQzWXI0Tk94Vk8rdDRvanhWNWdqTkpFY3pPTXNTZFRPSGVqSitaZwpHOHdQclVqTjJOcm5kVk1FOXNRM3FqRDNubjdNYjN6TmhiQ3hwMk03R0NiSDMzRzJLZWtKRVJrSXBSUzQ2MDMrCm93SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlYKSFE0RUZnUVVRenFrbjFUOHEyYVFMa015QUVUTXluS3pLZFl3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdhSQpaM3pZbm41Y3k2VWhwNUkxUWsrYUovVit2dXEzNG1oSWVMYUVEU0hubVlBN0FmWXlRUmIwZUFmSkRQU29hWEFvCkdLNjAxblhEZUZnRHdFWEdONGJneWVCNXFuTytSeVFYc3VhZE5UNWZSRG51TGc1VkFpL1JxTEMwYVpxMGowUlQKTTBQNFhZSFBJTXN4L04wQmlaa1NLZXEzemd4RDQ4Sk5WZVJaUHlzSGsrZHdHaWZvek9JT2xESzhWQlpiZTlyOAorTlNxL0VYMHNpNGY3bUdLeWFkb1ljZTJxT1o0V0dQd0pOWUNOdEwxVEtrNFIxdzZERmRJWnoyQzU1OUFvMVZyCnNiQkJIdlpLYk1jUmZkNncvNlAvQURMSFV0TGxSK2lhOG8yMi9Qb3N0dFVPeXV2V2tqWlJ0VThXODEwb2R3U0gKcytBdU5UZUF1elpVVFQxSFdLdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  admissionReviewVersions: ["v1"]
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: admission-registry-mutate
webhooks:
- name: io.docker.admission-registry-mutate
  rules:
  - apiGroups:
    - ""
    - "apps"
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - deployments
    - services
  clientConfig:
    service:
      name: admission-registry
      namespace: default
      path: "/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURtakNDQW9LZ0F3SUJBZ0lVWUpsRWRxdUM1Rk15dit2dmNhV3pTOFFGdjNFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFXcHBibWN4RURBT0JnTlZCQWNUQjBKbAphV3BwYm1jeEREQUtCZ05WQkFvVEEwczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByClpXSmxjbTVsZEdWek1CNFhEVEkwTURVeE5URXlOVE13TUZvWERUSTVNRFV4TkRFeU5UTXdNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFXcHBibWN4RURBT0JnTlZCQWNUQjBKbGFXcHBibWN4RERBSwpCZ05WQkFvVEEwczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByWldKbGNtNWxkR1Z6Ck1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeXhoMHdnWk9Sa1UwU0YvOE1OVHoKR2lJUFFpSVJIZGVqN1NaTXVIN0lCdW5pWUIyN3lGZXl5SlBoRnV2RDc2azBwNnNSNXk5TXJudjJDMy80UEo2WQp0TUlnendnbDBxWVNoYzdLblRiY05yNUxrWG9oRi9iQzMyZzE2QU9rSWJRL2MrSVFTTHRtb2RheHJoUlZKSUJaCjNHaW9wNmE3ZkpmRFQ0UGxrZ1BVOU5VRjlTMmdtWmt6MW1nMGFxaG9lakdITitsMW1ERXhUVHFnYWllbHFZNGIKVmVsVjBobjVzaGpRanRUZE82TC95aElWUEQzWXI0Tk94Vk8rdDRvanhWNWdqTkpFY3pPTXNTZFRPSGVqSitaZwpHOHdQclVqTjJOcm5kVk1FOXNRM3FqRDNubjdNYjN6TmhiQ3hwMk03R0NiSDMzRzJLZWtKRVJrSXBSUzQ2MDMrCm93SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlYKSFE0RUZnUVVRenFrbjFUOHEyYVFMa015QUVUTXluS3pLZFl3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdhSQpaM3pZbm41Y3k2VWhwNUkxUWsrYUovVit2dXEzNG1oSWVMYUVEU0hubVlBN0FmWXlRUmIwZUFmSkRQU29hWEFvCkdLNjAxblhEZUZnRHdFWEdONGJneWVCNXFuTytSeVFYc3VhZE5UNWZSRG51TGc1VkFpL1JxTEMwYVpxMGowUlQKTTBQNFhZSFBJTXN4L04wQmlaa1NLZXEzemd4RDQ4Sk5WZVJaUHlzSGsrZHdHaWZvek9JT2xESzhWQlpiZTlyOAorTlNxL0VYMHNpNGY3bUdLeWFkb1ljZTJxT1o0V0dQd0pOWUNOdEwxVEtrNFIxdzZERmRJWnoyQzU1OUFvMVZyCnNiQkJIdlpLYk1jUmZkNncvNlAvQURMSFV0TGxSK2lhOG8yMi9Qb3N0dFVPeXV2V2tqWlJ0VThXODEwb2R3U0gKcytBdU5UZUF1elpVVFQxSFdLdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  admissionReviewVersions: ["v1"]
  sideEffects: None

